export const sections = [
  { slug: "hero", title: "Hero", description: "Above-the-fold landing headlines with primary calls to action." },
  { slug: "about", title: "About Us", description: "Company story, mission, and values layouts." },
  { slug: "gallery", title: "Gallery", description: "Image grids and showcases." },
  { slug: "testimonials", title: "Testimonials", description: "Social proof and customer quotes." },
  { slug: "footers", title: "Footers", description: "Site-wide footer layouts with links and legal." },
  { slug: "articles", title: "Articles", description: "Blog/article listing sections." },
  { slug: "cta", title: "Call To Action", description: "Conversion-focused banner sections." },
  { slug: "pricing", title: "Pricing", description: "Plan comparison and pricing tables." },
  { slug: "faq", title: "FAQ", description: "Frequently asked questions layouts." },
  { slug: "stats", title: "Stats & Logos", description: "Metrics rows and social-proof logo strips." },
  { slug: "team", title: "Team", description: "Team member grids." },
  { slug: "contact", title: "Contact", description: "Contact forms and newsletter signups." },
];

export const elements = [
  { slug: "article-card", title: "Article Card", description: "Blog post preview cards." },
  { slug: "navbar", title: "Navbar", description: "Top site navigation bars." },
  { slug: "button", title: "Button", description: "Primary interactive buttons." },
  { slug: "map", title: "Map", description: "Location maps with pins, built with pure SVG/CSS." },
  { slug: "pdf-viewer", title: "PDF Viewer", description: "Real in-browser PDF rendering with react-pdf." },
  { slug: "card", title: "Card", description: "General-purpose content cards." },
  { slug: "badge", title: "Badge / Tag", description: "Small status and label indicators." },
  { slug: "modal", title: "Modal", description: "Dialog / overlay windows." },
  { slug: "accordion", title: "Accordion", description: "Expandable/collapsible content panels." },
  { slug: "tabs", title: "Tabs", description: "Tabbed content switchers." },
  { slug: "form-input", title: "Form Input", description: "Text inputs and form fields." },
  { slug: "avatar", title: "Avatar", description: "User profile picture displays." },
  { slug: "pagination", title: "Pagination", description: "Page navigation controls." },
  { slug: "breadcrumb", title: "Breadcrumb", description: "Hierarchical page location trails." },
  { slug: "stat-counter", title: "Stat Counter", description: "Highlighted numeric metrics." },
  { slug: "timeline", title: "Timeline", description: "Chronological step/event displays." },
  { slug: "carousel", title: "Carousel", description: "Sliding content carousels." },
  { slug: "toast", title: "Toast / Alert", description: "Transient notification messages." },
];
